language: node_js
before_script:
- chmod +x ./prebuild.sh
- ./prebuild.sh
- echo "phingbrasil.com.br" >> CNAME
script:
- docpad deploy-ghpages --env static
env:
  global:
  - GH_REPO="phing-brasil/phing-docs"
